# Generated by Django 4.2.5 on 2023-10-27 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followingrelation",
            name="follower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="followingrelation",
            name="following",
        ),
        migrations.AddField(
            model_name="followingrelation",
            name="following",
            field=models.ForeignKey(
                # default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
