# Generated by Django 4.2.5 on 2023-10-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="library_latitude",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="library_longitude",
            field=models.FloatField(null=True),
        ),
    ]
