# Generated by Django 4.2.5 on 2023-11-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_followingrelation_follower_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="library_latitude",
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="library_longitude",
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_message",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
