# Generated by Django 4.2.5 on 2023-10-05 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_library_latitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowingRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_user_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follower",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user_id",
                    models.ManyToManyField(
                        related_name="followee", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
