# Generated by Django 4.2.5 on 2023-10-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="readingrelation",
            old_name="book_isbn",
            new_name="book",
        ),
        migrations.RenameField(
            model_name="readingrelation",
            old_name="user_id",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="book",
            name="cover_image",
            field=models.ImageField(
                blank=True, upload_to="books/cover", verbose_name="표지 이미지"
            ),
        ),
    ]
