# Generated by Django 4.2.5 on 2023-11-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_alter_readingrelation_add_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="readingrelation",
            name="reading_progress",
            field=models.FloatField(default=0),
        ),
    ]
