# Generated by Django 4.2.5 on 2023-11-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_readingrelation_reading_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="readingrelation",
            name="rate",
            field=models.FloatField(null=True),
        ),
    ]
