# Generated by Django 4.2.5 on 2023-11-07 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_alter_readingrelation_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="readingrelation",
            name="reading_duration",
            field=models.DurationField(default=0),
        ),
    ]
