# Generated by Django 4.2.5 on 2023-10-27 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("add_date", models.DateField()),
                ("last_modify", models.DateField()),
                (
                    "reading_relation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.readingrelation",
                    ),
                ),
            ],
        ),
    ]
