# Generated by Django 4.2.5 on 2023-11-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="add_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="note",
            name="last_modify",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
